Datasets = c( "Tab1.10.csv", "Tab1.2.csv", "Tab1.3.csv", "Tab1.5.csv", "Tab1.6.csv", "Tab1.7.csv", "Tab1.8.csv", "Tab1.9.csv", "Tab11.10.csv", "Tab11.2.csv", "Tab11.4.csv", "Tab11.7.csv", "Tab11.8.csv", "Tab11.8b.csv", "Tab11.9.csv", "Tab3.2.csv", "Tab4.3.csv", "Tab4.6.csv", "Tab5.1.csv", "Tab5.11.csv", "Tab5.12.csv", "Tab5.2.csv", "Tab5.9.csv", "Tab6.10.csv", "Tab6.11.csv", "Tab6.12.csv", "Tab6.15.csv", "Tab6.16.csv", "Tab6.18.csv", "Tab6.19.csv", "Tab6.20.csv", "Tab6.5.csv", "Tab6.6.csv", "Tab6.7.csv", "Tab6.8.csv", "Tab6.9.csv", "Tab7.4.csv", "Tab7.5.csv", "Tab7.7.csv", "Tab8.5.csv", "Tab8.6.csv", "Tab8.7.csv" )

for(Dataset in Datasets){
    Dataname = paste0("JW_", sub(".csv", "", Dataset))
    Data=read.csv(paste0("https://R-Resources.massey.ac.nz/data/JohnsonWichern/", Dataset )) 
    assign(Dataname, Data)
    }

usethis::use_data(JW_Tab1.10, overwrite=TRUE)
usethis::use_data(JW_Tab1.2, overwrite=TRUE)
usethis::use_data(JW_Tab1.3, overwrite=TRUE)
usethis::use_data(JW_Tab1.5, overwrite=TRUE)
usethis::use_data(JW_Tab1.6, overwrite=TRUE)
usethis::use_data(JW_Tab1.7, overwrite=TRUE)
usethis::use_data(JW_Tab1.8, overwrite=TRUE)
usethis::use_data(JW_Tab1.9, overwrite=TRUE)
usethis::use_data(JW_Tab11.10, overwrite=TRUE)
usethis::use_data(JW_Tab11.2, overwrite=TRUE)
usethis::use_data(JW_Tab11.4, overwrite=TRUE)
usethis::use_data(JW_Tab11.7, overwrite=TRUE)
usethis::use_data(JW_Tab11.8, overwrite=TRUE)
usethis::use_data(JW_Tab11.8b, overwrite=TRUE)
usethis::use_data(JW_Tab11.9, overwrite=TRUE)
usethis::use_data(JW_Tab3.2, overwrite=TRUE)
usethis::use_data(JW_Tab4.3, overwrite=TRUE)
usethis::use_data(JW_Tab4.6, overwrite=TRUE)
usethis::use_data(JW_Tab5.1, overwrite=TRUE)
usethis::use_data(JW_Tab5.11, overwrite=TRUE)
usethis::use_data(JW_Tab5.12, overwrite=TRUE)
usethis::use_data(JW_Tab5.2, overwrite=TRUE)
usethis::use_data(JW_Tab5.9, overwrite=TRUE)
usethis::use_data(JW_Tab6.10, overwrite=TRUE)
usethis::use_data(JW_Tab6.11, overwrite=TRUE)
usethis::use_data(JW_Tab6.12, overwrite=TRUE)
usethis::use_data(JW_Tab6.15, overwrite=TRUE)
usethis::use_data(JW_Tab6.16, overwrite=TRUE)
usethis::use_data(JW_Tab6.18, overwrite=TRUE)
usethis::use_data(JW_Tab6.19, overwrite=TRUE)
usethis::use_data(JW_Tab6.20, overwrite=TRUE)
usethis::use_data(JW_Tab6.5, overwrite=TRUE)
usethis::use_data(JW_Tab6.6, overwrite=TRUE)
usethis::use_data(JW_Tab6.7, overwrite=TRUE)
usethis::use_data(JW_Tab6.8, overwrite=TRUE)
usethis::use_data(JW_Tab6.9, overwrite=TRUE)
usethis::use_data(JW_Tab7.4, overwrite=TRUE)
usethis::use_data(JW_Tab7.5, overwrite=TRUE)
usethis::use_data(JW_Tab7.7, overwrite=TRUE)
usethis::use_data(JW_Tab8.5, overwrite=TRUE)
usethis::use_data(JW_Tab8.6, overwrite=TRUE)
usethis::use_data(JW_Tab8.7, overwrite=TRUE)
